version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lofeback-postgres
    environment:
      POSTGRES_USER: lofebackuser
      POSTGRES_PASSWORD: lofebackpassword
      POSTGRES_DB: lofeback
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lofebackuser -d lofeback"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lofeback
      SPRING_DATASOURCE_USERNAME: lofebackuser
      SPRING_DATASOURCE_PASSWORD: lofebackpassword
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data: